name: Teste

on:
  push:
    branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Ação para fazer checkout do repositório

    - name: Setup Python version
      uses: actions/setup-python@v2 # Ação para configurar a versão do Python
      with:
        python-version: '3.*' # Versão do Python a ser utilizada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Instala as dependências listadas em requirements.txt

    - name: Run tests
      run: python -m unittest discover -s . # Comando para rodar os testes